### ISSUE TITLE
lib文件

### ISSUE THREAD

**Issue by iCodek** [huanghaozi/QRDetectorAndTracker#1]
博主您好，为什么我总是运行不起来，是你没给lib文件吗

**Comment by huanghaozi** [comment]
具体提示的是哪些lib/dll呀？

**Comment by iCodek** [comment]
> 具体提示的是哪些lib/dll呀？

opencv contrib编译的lib 比如tracking的lib，还有zbar的64位lib和libiconv.lib。
不过这些都难不倒我。跑出来效果不是很好，小目标不是很理想，还把我衣服误识别了

**Comment by huanghaozi** [comment]
> > 具体提示的是哪些lib/dll呀？
> 
> opencv contrib编译的lib 比如tracking的lib，还有zbar的64位lib和libiconv.lib。
> 不过这些都难不倒我。跑出来效果不是很好，小目标不是很理想，还把我衣服误识别了

这样啊，我这边测试用手机发光出来的二维码，效果不太好，用普通纸张会好很多，和环境光线、摄像头也有很大关系，可能纯视觉没法自适应这些，我正在加料。

**Comment by huanghaozi** [comment]
我还有个想法就是，用双目视觉的方法能弄出深度图，不过要用到匹配算法，估计会比较慢，不知道用FPGA去整速度会不会高些...
如果要检测的区域距离比较近，就可以根据距离来切割图像，把较近的提取出来，然后再对切割出来的图进行直方图均衡化，这样光线的问题可能会改善很多。
（不过多一个摄像头成本也会增加...）

**Comment by CirnoChyan** [comment]
我的也是，编译报错，namespace“cv”没有成员“Tracker”，请问如何解决呢？

**Comment by huanghaozi** [comment]
> 我的也是，编译报错，namespace“cv”没有成员“Tracker”，请问如何解决呢？

可能是编译器位数的问题吧，opencv和zbar的那堆.dll我用的是mingw的32位编译器编译的...

**Comment by huanghaozi** [comment]
> 我的也是，编译报错，namespace“cv”没有成员“Tracker”，请问如何解决呢？

可以自行编译一下opencv

**Comment by iCodek** [comment]
> > 我的也是，编译报错，namespace“cv”没有成员“Tracker”，请问如何解决呢？
> 
> 可以自行编译一下opencv

Tracker是opencv contrib的模块

**Comment by CirnoChyan** [comment]
> > 我的也是，编译报错，namespace“cv”没有成员“Tracke

> > 我的也是，编译报错，namespace“cv”没有成员“Tracker”，请问如何解决呢？
> 
> 可以自行编译一下opencv

明白了，谢谢，我编译试一下

**Comment by huanghaozi** [comment]
> > 具体提示的是哪些lib/dll呀？
> 
> opencv contrib编译的lib 比如tracking的lib，还有zbar的64位lib和libiconv.lib。
> 不过这些都难不倒我。跑出来效果不是很好，小目标不是很理想，还把我衣服误识别了

唔，我找到更好的Marker定位方案了，OpenCV的contrib库里**ArUco**效果很好，二维码终究还是不适合目标定位
